### PR TITLE
Adding Depmap 24Q2 data to dmsets()

### PR DESCRIPTION
**Pull request by apeltzer**
Let me know @lgatto if I need to change changelog / adapt things on the PR.

### CODE REVIEW

**Comment by lgatto** [comment]
Thanks! 

Could you:
- bump the version to 1.19.1 (I've just synced it with Bioconductor)
- add an entry for 1.19.1 in the NEWS.md file
- add yourself as contributor in the DESCRIPTION file

so that I can merge and push to Bioconductor.

**Comment by apeltzer** [comment]
Absolutely :)

**Comment by apeltzer** [comment]
Done @lgatto  - let me know if this is ok 👍🏻  And thanks for making the package :)

**Review by lgatto — APPROVED** [review]
Thank you for your contribution!  Just one detail, I'll credit you as 'ctb' (see ?person) in the DESCRIPTION file.  I will merge and push to Bioc right away, and should become available with BiocManager::install() within a couple ff days.

**Comment by apeltzer** [comment]
> Thank you for your contribution! Just one detail, I'll credit you as 'ctb' (see ?person) in the DESCRIPTION file. I will merge and push to Bioc right away, and should become available with BiocManager::install() within a couple ff days.

Absolutely fine, didn't know this exists and looked up a few packages but couldn't find `ctb`. More appropriate 👍🏻

**Pull request merged**
